### ISSUE TITLE
api structure document 

### ISSUE THREAD

**Issue by Avi-ADAM** [itswadesh/svelte-commerce#51]
hallo , its the best ecommerce tamlet i came a cross so far
i want to integrate it with my Strapi backend, is it possible? where can he api structure so i can make my api the same

**Comment by itswadesh** [comment]
Thank you Adam,
Yes it is possible to integrate with Strapi backend. 
Just need to change the endpoints under https://github.com/itswadesh/svelte-commerce/tree/master/src/lib)/services/
If you can, please push the Strapi integration back to the repo so that other can use it too. If you need any help understanding the architecture we can have a call https://calendly.com/misiki/15min
