### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by StevenChege** [itswadesh/svelte-commerce#70]
**Description**
I have a `medusajs` backend. I cloned this repo, added medusa-backend-url in `.env` file, exported medusa in the `src/lib/services/index.ts` directory, then installed dependencies. When i run the app it starts correctly but brings an error(shown below) and the server stops. Is there anything i'm missing?

**Error message**
> svelte-commerce@2023.05.06 dev
> node src/lib/services/copy && vite dev --host --port 3000

  VITE v4.3.7  ready in 27283 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.22.112:3000/
  ➜  Network: http://10.42.0.1:3000/
  ➜  press h to show help
10:21:04 AM [vite-plugin-svelte] /node_modules/svelte-toasts/src/FlatToast.svelte:37:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
10:21:07 AM [vite-plugin-svelte] /node_modules/svelte-toasts/src/BootstrapToast.svelte:23:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by ashok-cse** [comment]
Can you please screenshot or video for that issue?

**Comment by StevenChege** [comment]
![20230519_223224_mfnr.jpg](https://github.com/itswadesh/svelte-commerce/assets/99502290/041c8199-9838-42d3-9733-edc05cf547f8)

**Comment by acidlake** [comment]
I have the same error

**Comment by StevenChege** [comment]
Thanks @acidlake, but i still can't make it work. I found the issue stems from my medusa server, with `ProductCategory` `id` missing or mismatch . What ProductCategory schema is compatible? 
Here is a screenshot. 
![aa](https://github.com/itswadesh/svelte-commerce/assets/99502290/b172d770-0e5d-40f7-807e-0e409e20554d)

**Comment by itswadesh** [comment]
@acidlake The categories from medusa server looks fine. Is svelte-commerce working fine your side?

**Comment by acidlake** [comment]
@itswadesh so far is a mixbag, but i manage to successfully connect, i'm doing changes on svelte-commerce source code to make it work as expected, search don't work, homepage don't show anything, categories are working, but product details is not, still lot of things to fix, once im done il see if i can do a PR, and check if the owner of svelte-commerce accept it, if no il share a repo

**Comment by itswadesh** [comment]
@acidlake Please do the PR. I will try to merge it as fast as possible, we are looking for such contribution towards medusajs integration. With litekart backend svelte-commerce is working excellent. Our next target is to finish up MedusaJs.

**Comment by acidlake** [comment]
@itswadesh o thanks a lot, my bad, dint't notice that you are the creator of the repo, il do the PR once im done!!, very great product!

**Comment by acidlake** [comment]
Ok guys, quick update, so far good progress, here is how the product page looks, i also created a basic image gallery for the product detail page, so far working great with medusa, il continue with the other fixes.

<img width="1782" alt="Screenshot 2023-06-07 at 3 39 06 PM" src="https://github.com/itswadesh/svelte-commerce/assets/4008759/16ad1570-be56-44d1-846f-d64928c3b322">

**Comment by michaldshefing** [comment]
@acidlake if you have anything to share in a fork please share , it will be really appreciated - thank you

**Comment by saimyst** [comment]
@acidlake Can you please share?

**Comment by tsemachh** [comment]
@acidlake if you can share we can try to give a hand there

**Comment by acidlake** [comment]
Hello there, sorry I've been busy at work and with the family, got a new family member, i will create a PR today, if you guys can wait a little longer.

Thanks and sorry for the delay

**Comment by acidlake** [comment]
Hello guys, sorry for the time, at first i as doing the changes for my project, however i did a lot of changes to the project that break the other integrations, such as woocomerce, bigcommerce etc, my suggesstion is to create some sort of adapters, that we can plug in for medusaje, woocomerce, bigcommerce etc, we may need to abstract and refactor the project, so the storefront should work with any adapter that we add, again, the modifications that i made as for my project, and since i was just using medusajs, it broke the other integrations, so an adaptar should work. or separate the project for medusajs only but that would created more work

**Comment by itswadesh** [comment]
Hi, thanks for the update. Can you please push it to a different branch, so that we can have a look and make necessary changes to keep other services working and eventually merge it into master.

We though of making a adaptor for each of those services, where as it would make the developer experience difficult, like F12 key won't work to navigate to the exact method. 

Ideas are welcome.

**Comment by tsemachh** [comment]
Thank you @acidlake and congrats for the new member.
As for the right way to decouple , I think we will be smarter once we see the actual changes.
As long as we stick with having all adaptors in same repo and uncommenting the implementation we want
, the files navigation will depends on the IDE used I believe(I use InteliJ and it leads me to the right file)
If we keep it all in monorepo with dependencies to the adaptors it may help with the navigation issue , and maybe in general will be good evolution.

**Comment by tsemachh** [comment]
@acidlake and @itswadesh 
I started reviewing the current Medusa APIs , most of them are not working as expected , 
While medusa BE expects mainly Ids , APIs are working with slug(Or handle in mesua terms)
There's a need to call other APIs to accomplish that.
(Sometimes more than one , unless we change the call to pass both slug and Id)
Also I noticed that APIs called are not calling the exact API needed for example getting category products returns all products.
I guess there are more to follow.
One more thing , sometimes the APIs are called from the UI , sometimes from from the server.js , 
I would expect some consistency , as my knowledge in sveltekit preparing the data to the page should be in server.js
(This alone can solve CORS issue we may have with the BE)
@acidlake if you can make the branch I think I can take it from there

Tsemach

**Comment by itswadesh** [comment]
> Thank you @acidlake and congrats for the new member. As for the right way to decouple , I think we will be smarter once we see the actual changes. As long as we stick with having all adaptors in same repo and uncommenting the implementation we want , the files navigation works on both IJ and Code. If we keep it all in monorepo with dependencies to the adaptors it may help with the navigation issue , and maybe in general will be good evolution.

@tsemachh thank you so much for taking time studying the under laying structure and the suggestion. If it solves the file navigations issue, surely mono repo will be a good idea. Would it be possible to setup the file structure, while @acidlake push the changes to a new branch or raise a pull request.

**Comment by tsemachh** [comment]
@itswadesh I do prefer to get @acidlake PR first so I will have full view of the changes made .
What I can say in general  2 things:
1. In some point if this project evolves to something big it's better to have API and Themes available as plugins 
2. As for APIs - APIs called to prepare the page should be in the relevant server.js/ts calls , other APIs can be either invoked from the page itself or call API end points on the server which will perform the actual call.
In other project I did I also had the retrieve APIs using API endpoints , this really helped when I used partial SSG for the API calls 
in our case , categories and product pages data can be pre generated as an API and updated on changes

**Comment by itswadesh** [comment]
> 

@tsemachh  This is interesting, and will give a lot of performance improvements. However I have following questions.

1. Do we need to rebuild the repo each time the category or product info changes
2. What if I have a million products, will it be a good idea?

**Comment by tsemachh** [comment]
Basically in order to support incremental SSG there's a [case](https://github.com/sveltejs/kit/issues/661) opened ,
And Vercel has support for it if you run there - https://vercel.com/docs/concepts/incremental-static-regeneration.
Since this is the case , what I did in other project is to generate just the changes and deploy them into the site.
You can define when you generate the changes which routes to re-generate , this way you can have better control of what's generated without waiting for case resolution.
BTW: I did saw that the project does not support product variants which is basic for our case in MedusaJs so we may choose another StoreFront (Unless @acidlake provided decent support for it)

**Comment by acidlake** [comment]
Hello Guys, i'm working on the PR at this moment, since originally i fixing the project for my own storefront with different requirements etc, and i was removing everything related to the other backends, since i was keeping medusajs, i created a new fork, and im uploading my changes.

**Comment by tsemachh** [comment]
Awesome, thanks for the update!

**Comment by itswadesh** [comment]
Started looking into all the pull requests. Let's connect on discord before merging so that we can discuss all the aspects to it

I will be available 11:00-19:00 GMT

**Comment by acidlake** [comment]
i see some comments regardles break of SaaS, when i checked this project i was testing medusajs, but since the storefront needs a loot of work and medusajs still lacks some features, i switched to Saleor, but i decided to create a storefront from scratch, that's why i took to long to upload the changes, since i was already finish with the testings in this project and medusa and i deleted that repo, but didn't know that this project was part of a SaaS, my suggest is to focus on one storefront at the time, for example, i see the project is very harcoded to support litekart, which i asume is your SaaS, in order to support more backends and have better customization, better DX, is better to create a generic solution, with adapters, or services that can be easy switch, and customized for that spesific project, i added an option to switch from one service to other very easy, but like i say, the project is too heavy on litekart, so it would be better to drop the support for medusajs, and be focus on litekart

**Comment by itswadesh** [comment]
We are committed to integrate as many storefronts we can, and this repo has that capability.

Medusa is still under heavy development. To make the storefront fully functional we 1st tried to integrate with Litekart which is working 100%. Next step is to integrate Medusajs. 

Regarding SaaS compatibility, there is only 1 line that has to be changed.

Regarding Medusajs compatibility we are also working on it in sync with Medusa development, and have completed a lot of integration, its just matter of cleanup and some branch merger.

We are keeping it all together just for simplicity and developer experience. 

@acidlake if you can create a pull request on the feat/medusajs-api-integration branch instead of master, I will have a look how can we make it compatible with both the ecommerce platforms.

**Comment by itswadesh** [comment]
@tsemachh Thank you so much for your insights.

I am trying my best to accommodate different store api without breaking each other.

**Comment by itswadesh** [comment]
@tsemachh @acidlake Merged the pull request to the master. I had to take down 1-2 commits just the keep the dev experience upto the mark.

**Comment by acidlake** [comment]
nice, should we close this issue, since the Unhandled promise rejection get solved with the PR merged to master

**Comment by tsemachh** [comment]
@itswadesh and @acidlake - thank you very much for pushing it forward.
@itswadesh is there any branch which has medusajs API changes ? we still see gaps and would like to add our insights there.

**Comment by itswadesh** [comment]
Medusa is merged into master, can be activated from `services/index.ts` file.
Can you please specify the exact error

**Comment by tsemachh** [comment]
Many of the APIs are not functioning properly:
- Getting products of category - brings all products
- The search products API is not written in the right way should pass query in the body of the post API
- Adding product to cart produces Undefined , something is not correlated to the right structure
- Price is not coming the right way , should be processed
- No dedicated code for Variants and their options
We didn't check all APIs but I think besides not failing , the basic should integrated with seeded medusa BE

**Comment by itswadesh** [comment]
Thanks @tsemachh for letting us know, the issues are fixed now

1. Products of categories
2. Search products api
3. Add to cart
4. Price coming now
5. Variants introduced
6. Basic checkout flow is working.

**Comment by tsemachh** [comment]
Thank you @itswadesh it looks better from first view I still see the API:
fetchProductsOfCategory
		res = await getMedusajsApi(`products?category_id[]=${categorySlug}`)
category_id != categorySlug
You will need to get the id first and then use it in the API
Good luck though
